package my:virtualization;

world proxy {

    // === CLI and Core Interception ===
    include wasi:cli/imports@0.3.0;
    
    // Exports
    export wasi:cli/environment@0.3.0;
    export wasi:cli/exit@0.3.0;
    // wasi:filesystem/types has functions! We must export it to proxy them.
    export wasi:filesystem/types@0.3.0;
    export wasi:filesystem/preopens@0.3.0;

    // wasi:sockets/types has functions!
    export wasi:sockets/types@0.3.0;
    export wasi:sockets/ip-name-lookup@0.3.0;

    // === HTTP Interception ===
    import wasi:http/handler@0.3.0;
    import wasi:http/client@0.3.0;
    export wasi:http/handler@0.3.0;
    export wasi:http/client@0.3.0;
}
