FROM python:3.11-slim

RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*

WORKDIR /c2
COPY c2_server.py /c2/

# Run a python web server to listen for exfiltrated data
CMD ["python", "c2_server.py"]
