// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod local {
        pub mod telemetry_demo {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod processor {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// A structured data payload
                #[derive(Clone)]
                pub struct SensorReading {
                    pub sensor_id: _rt::String,
                    pub value: f64,
                    pub timestamp: u64,
                }
                impl ::core::fmt::Debug for SensorReading {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SensorReading")
                            .field("sensor-id", &self.sensor_id)
                            .field("value", &self.value)
                            .field("timestamp", &self.timestamp)
                            .finish()
                    }
                }
                /// A structured error definition
                #[derive(Clone)]
                pub enum ProcessingError {
                    CorruptedData(_rt::String),
                    SensorOffline,
                    LimitExceeded,
                }
                impl ::core::fmt::Debug for ProcessingError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ProcessingError::CorruptedData(e) => {
                                f.debug_tuple("ProcessingError::CorruptedData")
                                    .field(e)
                                    .finish()
                            }
                            ProcessingError::SensorOffline => {
                                f.debug_tuple("ProcessingError::SensorOffline").finish()
                            }
                            ProcessingError::LimitExceeded => {
                                f.debug_tuple("ProcessingError::LimitExceeded").finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for ProcessingError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for ProcessingError {}
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_async_analyze_batch_cabi<T: Guest>(
                    arg0: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::async_analyze_batch(
                        wit_bindgen_rt::async_support::StreamReader::from_handle_and_vtable(
                            arg0 as u32,
                            &super::super::super::super::wit_stream::vtable0::VTABLE,
                        ),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                ProcessingError::CorruptedData(e) => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec3 = (e.into_bytes()).into_boxed_slice();
                                    let ptr3 = vec3.as_ptr().cast::<u8>();
                                    let len3 = vec3.len();
                                    ::core::mem::forget(vec3);
                                    *ptr1
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len3;
                                    *ptr1
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr3.cast_mut();
                                }
                                ProcessingError::SensorOffline => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                }
                                ProcessingError::LimitExceeded => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                }
                            }
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_async_analyze_batch<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l3 {
                                0 => {
                                    let l4 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l4, l5, 1);
                                }
                                1 => {}
                                _ => {}
                            }
                        }
                    }
                }
                pub trait Guest {
                    /// Streams a batch of readings, returns a future containing a Result
                    fn analyze_batch(
                        readings: wit_bindgen_rt::async_support::StreamReader<
                            SensorReading,
                        >,
                    ) -> Result<_rt::String, ProcessingError>;
                }
                #[doc(hidden)]
                macro_rules! __export_local_telemetry_demo_processor_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "local:telemetry-demo/processor@0.1.0#[async]analyze-batch")]
                        unsafe extern "C" fn export_async_analyze_batch(arg0 : i32,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_async_analyze_batch_cabi::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_local:telemetry-demo/processor@0.1.0#[async]analyze-batch")]
                        unsafe extern "C" fn _post_return_async_analyze_batch(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_async_analyze_batch::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_local_telemetry_demo_processor_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::alloc;
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
pub mod wit_stream {
    #![allow(dead_code, unused_variables, clippy::all)]
    pub trait StreamPayload: Unpin + Sized + 'static {
        const VTABLE: &'static wit_bindgen_rt::async_support::StreamVtable<Self>;
    }
    #[doc(hidden)]
    pub mod vtable0 {
        fn write(
            stream: u32,
            values: &[super::super::exports::local::telemetry_demo::processor::SensorReading],
        ) -> ::core::pin::Pin<
            super::super::_rt::Box<dyn ::core::future::Future<Output = usize> + '_>,
        > {
            super::super::_rt::Box::pin(async move {
                let address = unsafe {
                    super::super::_rt::alloc::alloc(
                        super::super::_rt::alloc::Layout::from_size_align_unchecked(
                            24 * values.len(),
                            8,
                        ),
                    )
                };
                for (index, value) in values.iter().enumerate() {
                    let address = unsafe { address.add(index * 24) };
                    unsafe {
                        let super::super::exports::local::telemetry_demo::processor::SensorReading {
                            sensor_id: sensor_id0,
                            value: value0,
                            timestamp: timestamp0,
                        } = value;
                        let vec1 = sensor_id0;
                        let ptr1 = vec1.as_ptr().cast::<u8>();
                        let len1 = vec1.len();
                        *address
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len1;
                        *address.add(0).cast::<*mut u8>() = ptr1.cast_mut();
                        *address
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<f64>() = super::super::_rt::as_f64(value0);
                        *address
                            .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                            .cast::<i64>() = super::super::_rt::as_i64(timestamp0);
                    }
                }
                let mut total = 0;
                while total < values.len() {
                    match unsafe {
                        wit_bindgen_rt::async_support::await_stream_result(
                                start_write,
                                stream,
                                address.add(total * 24),
                                u32::try_from(values.len() - (total * 24)).unwrap(),
                            )
                            .await
                    } {
                        wit_bindgen_rt::async_support::AsyncWaitResult::Values(count) => {
                            total += count;
                        }
                        wit_bindgen_rt::async_support::AsyncWaitResult::Error(_) => {
                            unreachable!("encountered error during write")
                        }
                        wit_bindgen_rt::async_support::AsyncWaitResult::End => break,
                    }
                }
                total
            })
        }
        fn read(
            stream: u32,
            values: &mut [::core::mem::MaybeUninit<
                super::super::exports::local::telemetry_demo::processor::SensorReading,
            >],
        ) -> ::core::pin::Pin<
            super::super::_rt::Box<
                dyn ::core::future::Future<
                    Output = ::std::option::Option<
                        ::std::result::Result<
                            usize,
                            wit_bindgen_rt::async_support::ErrorContext,
                        >,
                    >,
                > + '_,
            >,
        > {
            super::super::_rt::Box::pin(async move {
                let address = unsafe {
                    super::super::_rt::alloc::alloc(
                        super::super::_rt::alloc::Layout::from_size_align_unchecked(
                            24 * values.len(),
                            8,
                        ),
                    )
                };
                match unsafe {
                    wit_bindgen_rt::async_support::await_stream_result(
                            start_read,
                            stream,
                            address,
                            u32::try_from(values.len()).unwrap(),
                        )
                        .await
                } {
                    wit_bindgen_rt::async_support::AsyncWaitResult::Values(count) => {
                        for (index, dst) in values.iter_mut().take(count).enumerate() {
                            let address = unsafe { address.add(index * 24) };
                            let value = unsafe {
                                let l0 = *address.add(0).cast::<*mut u8>();
                                let l1 = *address
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len2 = l1;
                                let bytes2 = super::super::_rt::Vec::from_raw_parts(
                                    l0.cast(),
                                    len2,
                                    len2,
                                );
                                let l3 = *address
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<f64>();
                                let l4 = *address
                                    .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<i64>();
                                super::super::exports::local::telemetry_demo::processor::SensorReading {
                                    sensor_id: super::super::_rt::string_lift(bytes2),
                                    value: l3,
                                    timestamp: l4 as u64,
                                }
                            };
                            dst.write(value);
                        }
                        Some(Ok(count))
                    }
                    wit_bindgen_rt::async_support::AsyncWaitResult::Error(e) => {
                        Some(
                            Err(
                                wit_bindgen_rt::async_support::ErrorContext::from_handle(e),
                            ),
                        )
                    }
                    wit_bindgen_rt::async_support::AsyncWaitResult::End => None,
                }
            })
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn cancel_write(_: u32) -> u32 {
            unreachable!()
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn cancel_read(_: u32) -> u32 {
            unreachable!()
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn close_writable(_: u32, _: u32) {
            unreachable!()
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn close_readable(_: u32, _: u32) {
            unreachable!()
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn new() -> u32 {
            unreachable!()
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn start_read(_: u32, _: *mut u8, _: u32) -> u32 {
            unreachable!()
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn start_write(_: u32, _: *mut u8, _: u32) -> u32 {
            unreachable!()
        }
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "[export]local:telemetry-demo/processor@0.1.0")]
        unsafe extern "C" {
            #[link_name = "[stream-new-0][async]analyze-batch"]
            fn new() -> u32;
            #[link_name = "[stream-cancel-write-0][async]analyze-batch"]
            fn cancel_write(_: u32) -> u32;
            #[link_name = "[stream-cancel-read-0][async]analyze-batch"]
            fn cancel_read(_: u32) -> u32;
            #[link_name = "[stream-close-writable-0][async]analyze-batch"]
            fn close_writable(_: u32, _: u32);
            #[link_name = "[stream-close-readable-0][async]analyze-batch"]
            fn close_readable(_: u32, _: u32);
            #[link_name = "[async-lower][stream-read-0][async]analyze-batch"]
            fn start_read(_: u32, _: *mut u8, _: u32) -> u32;
            #[link_name = "[async-lower][stream-write-0][async]analyze-batch"]
            fn start_write(_: u32, _: *mut u8, _: u32) -> u32;
        }
        pub static VTABLE: wit_bindgen_rt::async_support::StreamVtable<
            super::super::exports::local::telemetry_demo::processor::SensorReading,
        > = wit_bindgen_rt::async_support::StreamVtable::<
            super::super::exports::local::telemetry_demo::processor::SensorReading,
        > {
            write,
            read,
            cancel_write,
            cancel_read,
            close_writable,
            close_readable,
            new,
        };
        impl super::StreamPayload
        for super::super::exports::local::telemetry_demo::processor::SensorReading {
            const VTABLE: &'static wit_bindgen_rt::async_support::StreamVtable<Self> = &VTABLE;
        }
    }
    /// Creates a new Component Model `stream` with the specified payload type.
    pub fn new<T: StreamPayload>() -> (
        wit_bindgen_rt::async_support::StreamWriter<T>,
        wit_bindgen_rt::async_support::StreamReader<T>,
    ) {
        unsafe { wit_bindgen_rt::async_support::stream_new::<T>(T::VTABLE) }
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_telemetry_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::local::telemetry_demo::processor::__export_local_telemetry_demo_processor_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::local::telemetry_demo::processor);
    };
}
#[doc(inline)]
pub(crate) use __export_telemetry_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:local:telemetry-demo@0.1.0:telemetry-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 410] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x94\x02\x01A\x02\x01\
A\x02\x01B\x08\x01r\x03\x09sensor-ids\x05valueu\x09timestampw\x04\0\x0esensor-re\
ading\x03\0\0\x01q\x03\x0ecorrupted-data\x01s\0\x0esensor-offline\0\0\x0elimit-e\
xceeded\0\0\x04\0\x10processing-error\x03\0\x02\x01f\x01\x01\x01j\x01s\x01\x03\x01\
@\x01\x08readings\x04\0\x05\x04\0\x14[async]analyze-batch\x01\x06\x04\0$local:te\
lemetry-demo/processor@0.1.0\x05\0\x04\0*local:telemetry-demo/telemetry-world@0.\
1.0\x04\0\x0b\x15\x01\0\x0ftelemetry-world\x03\0\0\0G\x09producers\x01\x0cproces\
sed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
